name: Publish

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Check version consistency
      run: |
        version=$(grep '^version' pyproject.toml | awk '{print $3}' | tr -d '"')
        tag=v$version
        if [ "$tag" != "${GITHUB_REF#refs/tags/}" ]; then
          echo "Error: version in pyproject.toml ($tag) does not match git tag (${GITHUB_REF#refs/tags/})"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pylint
        poetry config virtualenvs.create false
        poetry install --no-root --no-interaction --no-ansi --no-dev

    - name: Build package
      run: poetry build

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish

    - name: Attach built package to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/hcloud_selfdestruct-*.tar.gz
          dist/hcloud_selfdestruct-*-py3-none-any.whl 
